// Generated by CoffeeScript 1.7.1
var BigInteger, NTLMResponsePayload, WritableTrackingBuffer, crypto;

BigInteger = require("bignumber").BigInteger;

crypto = require("crypto");

WritableTrackingBuffer = require("./tracking-buffer/writable-tracking-buffer");

NTLMResponsePayload = (function() {
  NTLMResponsePayload = function(loginData) {
    this.data = this.createResponse(loginData);
  };
  NTLMResponsePayload.prototype.toString = function(indent) {
    indent || (indent = "");
    return indent + "NTLM Auth";
  };
  NTLMResponsePayload.prototype.createResponse = function(challenge) {
    var baseIdx, bufferLength, client_nonce, data, dnIdx, domain, genTime, l2Idx, lmv2Data, lmv2len, ntIdx, ntlmData, ntlmv2len, password, server_data, server_nonce, timestamp, unIdx, username;
    client_nonce = this.createClientNonce();
    lmv2len = 24;
    ntlmv2len = 16;
    domain = challenge.domain;
    username = challenge.userName;
    password = challenge.password;
    ntlmData = challenge.ntlmpacket;
    server_data = ntlmData.target;
    server_nonce = ntlmData.nonce;
    bufferLength = 64 + (domain.length * 2) + (username.length * 2) + lmv2len + ntlmv2len + 8 + 8 + 8 + 4 + server_data.length + 4;
    data = new WritableTrackingBuffer(bufferLength);
    data.position = 0;
    data.writeString("NTLMSSP\u0000", "utf8");
    data.writeUInt32LE(0x03);
    baseIdx = 64;
    dnIdx = baseIdx;
    unIdx = dnIdx + domain.length * 2;
    l2Idx = unIdx + username.length * 2;
    ntIdx = l2Idx + lmv2len;
    data.writeUInt16LE(lmv2len);
    data.writeUInt16LE(lmv2len);
    data.writeUInt32LE(l2Idx);
    data.writeUInt16LE(ntlmv2len);
    data.writeUInt16LE(ntlmv2len);
    data.writeUInt32LE(ntIdx);
    data.writeUInt16LE(domain.length * 2);
    data.writeUInt16LE(domain.length * 2);
    data.writeUInt32LE(dnIdx);
    data.writeUInt16LE(username.length * 2);
    data.writeUInt16LE(username.length * 2);
    data.writeUInt32LE(unIdx);
    data.writeUInt16LE(0);
    data.writeUInt16LE(0);
    data.writeUInt32LE(baseIdx);
    data.writeUInt16LE(0);
    data.writeUInt16LE(0);
    data.writeUInt32LE(baseIdx);
    data.writeUInt16LE(0x8201);
    data.writeUInt16LE(0x08);
    data.writeString(domain, "ucs2");
    data.writeString(username, "ucs2");
    lmv2Data = this.lmv2Response(domain, username, password, server_nonce, client_nonce);
    data.copyFrom(lmv2Data);
    genTime = (new Date).getTime();
    ntlmData = this.ntlmv2Response(domain, username, password, server_nonce, server_data, client_nonce, genTime);
    data.copyFrom(ntlmData);
    data.writeUInt32LE(0x0101);
    data.writeUInt32LE(0x0000);
    timestamp = this.createTimestamp(genTime);
    data.copyFrom(timestamp);
    data.copyFrom(client_nonce);
    data.writeUInt32LE(0x0000);
    data.copyFrom(server_data);
    data.writeUInt32LE(0x0000);
    return data.data;
  };
  NTLMResponsePayload.prototype.createClientNonce = function() {
    var client_nonce, nidx;
    client_nonce = new Buffer(8);
    nidx = 0;
    while (nidx < 8) {
      client_nonce.writeUInt8(Math.ceil(Math.random() * 255), nidx);
      nidx++;
    }
    return client_nonce;
  };
  NTLMResponsePayload.prototype.ntlmv2Response = function(domain, user, password, serverNonce, targetInfo, clientNonce, mytime) {
    var data, dataLength, hash, newHash, timestamp;
    timestamp = this.createTimestamp(mytime);
    hash = this.ntv2Hash(domain, user, password);
    dataLength = 40 + targetInfo.length;
    data = new Buffer(dataLength);
    serverNonce.copy(data, 0, 0, 8);
    data.writeUInt32LE(0x101, 8);
    data.writeUInt32LE(0x0, 12);
    timestamp.copy(data, 16, 0, 8);
    clientNonce.copy(data, 24, 0, 8);
    data.writeUInt32LE(0x0, 32);
    targetInfo.copy(data, 36, 0, targetInfo.copy);
    data.writeUInt32LE(0x0, 36 + targetInfo.length);
    newHash = this.hmacMD5(data, hash);
    return newHash;
  };
  NTLMResponsePayload.prototype.createTimestamp = function(time) {
    var bigTime, idx, padded, result, timestamp;
    bigTime = new BigInteger("" + time);
    timestamp = bigTime.add(new BigInteger("" + 11644473600000)).multiply(new BigInteger("" + 10000)).toString(16);
    padded = "00000000" + timestamp;
    timestamp = padded.substr(padded - 16);
    result = new Buffer(8);
    idx = 8;
    while (idx > 0) {
      result[idx - 1] = parseInt(timestamp.substr(timestamp.length - (2 * idx), 2), 16);
      idx--;
    }
    return result;
  };
  NTLMResponsePayload.prototype.lmv2Response = function(domain, user, password, serverNonce, clientNonce) {
    var data, hash, newhash, response;
    hash = this.ntv2Hash(domain, user, password);
    data = new Buffer(serverNonce.length + clientNonce.length);
    serverNonce.copy(data, 0, 0, serverNonce.length);
    clientNonce.copy(data, serverNonce.length, 0, clientNonce.length);
    newhash = this.hmacMD5(data, hash);
    response = new Buffer(newhash.length + clientNonce.length);
    newhash.copy(response, 0, 0, newhash.length);
    clientNonce.copy(response, newhash.length, 0, clientNonce.length);
    return response;
  };
  NTLMResponsePayload.prototype.ntv2Hash = function(domain, user, password) {
    var hash, identity, result;
    hash = this.ntHash(password);
    identity = new Buffer(user.toUpperCase() + domain.toUpperCase(), "ucs2");
    result = this.hmacMD5(identity, hash);
    return result;
  };
  NTLMResponsePayload.prototype.ntHash = function(text) {
    var md4, result, unicodeString;
    result = new Buffer(21);
    result.fill(0);
    unicodeString = new Buffer(text, "ucs2");
    md4 = crypto.createHash("md4").update(unicodeString).digest();
    md4.copy(result, 0, 0, md4.length);
    return result;
  };
  NTLMResponsePayload.prototype.hmacMD5 = function(data, key) {
    var hmac;
    hmac = crypto.createHmac("MD5", key);
    hmac.update(data);
    return hmac.digest();
  };
  return NTLMResponsePayload;
})();

module.exports = NTLMResponsePayload;
